// lang-en.ts

export const LANG_EN_NAME = 'en';

export const LANG_EN_TRANS = {
	'DATE_FORMAT': 'mm/dd/yyyy',
	'DATE_SEPERATOR': '/',

	'hello world': 'hello world leader',
	'HOME': 'Home',
	'USER_ADMINISTRATION': 'User Administration',
	'PROJECT_MANAGEMENT': 'Project Management',
	'PROJECT_MANAGEMENT_ADMINISTRATION': 'Project Management Administration',
	'CREATED_WITH': 'Created with',
	'DC_COPYRIGHT': 'Dexter & Chaney, LLC. All rights reserved. No unauthorized access.',
	'DC_COPYRIGHT_YEAR': '1988-2017 ',
	'DC_WEB_PAGE_LINK': 'http://www.dexterchaney.com/',
	'EXTERNAL_LINK': 'External Link',
	'LOG_OFF': 'Log Out',
	'LOGGED_OFF': 'You have logged out of the application',
	'ACTION': 'Action',
	'USER_LIST': 'User List',
	'NICK_NAME': 'Nick Name',
	'GIVEN_NAME': 'First Name',
	'FAMILY_NAME': 'Last Name',
	'NAME': 'Name',
	'EMAIL': 'Email',
	'EMAIL_LOGON': 'E-mail / Logon',
	'LAST_LOGIN': 'Last Login',
	'CARD_STYLE': 'Card Style',
	'LABEL': 'Label',
	'HIDE': 'Hide',
	'CLASS': 'Class',
	'PLACEHOLDER': 'Placeholder',
	'REQ': 'Req',
	'READ': 'Read',
	'VERIFIED': 'Status',
	'1_COLUMN': '1-Column',
	'2_COLUMN': '2-Column',
	'3_COLUMN': '3-Column',
	'JOB': 'Job',
	'OWNER': 'Assigned',
	'SEND_TO': 'Send To',
	'PHASE': 'Phase',
	'DATE': 'Date',
	'DESCRIPTION': 'Description',
	'PROJECT_MANAGER': 'Project Manager',
	'REPORT_DATE': 'Report Date',
	'CARD_TITLE': 'Card Title',
	'REPORT_FLAGGED_REASONS': 'Report Flagged Reasons',
	'PHOTO_GALLERY': 'photo gallery',
	'FIELD_REPORT': 'Dashboard',
	'FIELD': 'Field',
	'SELECT_FIELD_COMPONENT': 'Select Form Component',
	
	'WEATHER': 'Weather',
	'TEMP': 'Temp',
	'WIND': 'Wind',
	'PRECIP': 'Precip',
	'EVENT': 'Event',
	'SKY': 'Sky',
	'GROUND': 'Ground',
	'WEATHER_DELAY': 'Weather Delay',
	'PHOTO_ATTACHMENTS': 'Photo Attachments',
	'PHOTO_ATTACHMENT': 'Photo Attachment',
	'CONDITION': 'Weather',
	'RH': 'RH',

	'SUBCONTRACTOR': 'Subcontractor Company',
	'WORKER_COUNT': 'Number of Workers',
	'NOTES': 'Notes',
	'CREW': 'Crew',

	'VISITOR_NAME': 'Name',
	'VISITOR': 'Visitor',
	'COMPANY': 'Company',
	'FOR': 'Reason for visit',
	'TO_SEE': 'Meeting with',
	'TIME_IN': 'Time In',
	'TIME': 'Time',
	'TIME_OUT': 'Time Out',
	'VISTOR_SIGNATURE': 'Signature',

	'WORK_COMPLETED': 'Work Completed',
	'LOCATION': 'Location',

	'PHOTO': 'Photo',
	'SIGNATURE': 'Signature',

	'OPEN_FIELD_REPORTS': 'Open Field Reports',
	'CLOSED_FIELD_REPORTS': 'Submitted Field Reports',

	'ERROR_ALL_LICENSES_ASSIGNED': 'All licenses have been assigned.',
	'ERROR_IS_REQUIRED': 'is required.',
	'ERROR_NO_DOCUMENTS_FOR_CATEGORY': 'No documents found for this category.',
	'ERROR_SOMETHING_BAD_HAPPENED': 'The update was not processed, please logoff and login or refresh the page.',
	'ERROR_RECORD_NOT_ADDED_DUPLICATE': 'The record was not added, it already exists in the database.',
	'ERROR_CANNOT_REMOVE_LICENSE': 'The admin license cannot be removed from this user.',
	'ERROR_IS_INVALID': 'is not valid.',
	'ERROR_DUPLICATE_FIELD_REPORT': 'A report for this job and date has already been created.',

	'INFO_DOCUMENTS_ADDED': 'documents added.',
	'INFO_DOCUMENT_ADDED': 'document added.',
	'INFO_DOCUMENT_DELETED': 'document deleted.',
	'INFO_RECORD_DELETED': 'record deleted.',
	'INFO_USER_DELETED': 'User deleted successfully.',
	'INFO_OK_DELETE_RECORD': 'Are you sure you want to delete ',
	'INFO_USER_ADDED': 'user added.',
	'INFO_ROUTING_FAILURE': 'Sorry, an error has occurred, Please press the button to display your page!',
	'INFO_OK_SUBMIT_FIELD_REPORT': 'Pressing OK will send this report to the Project Manager.',
	'INFO_FIELD_REPORT_SUBMITTED': 'The field report has been sent.',
	'INFO_OK_COPY_FIELD_REPORT': 'Pressing OK will copy this report and create a new field report.',
	'INFO_FIELD_REPORT_COPIED': 'The field report has been copied.',
	'INFO_OK_DELETE_FIELD_REPORT': 'Pressing OK will delete this report: ',
	'INFO_FIELD_REPORT_DELETED': 'The field report has been deleted.',
	'INFO_OK_DELETE_FIELD_REPORT_LOG': 'Pressing OK will delete this log entry: ',
	'INFO_FIELD_REPORT_LOG_DELETED': 'The field report log has been deleted.',

	'PLACEHOLDER_SEARCH': 'Search for ...',
	'TITLE_BACK_TO_TOP': 'Back to Top',
	'TITLE_ADD_NEW_USER': 'Add User',
	'TITLE_ROUTING_FAILURE': 'OOPS!',
	'FIELD_REPORTING': 'Field',
	'TITLE_ADD_FIELD_REPORT': 'New Field Report',
	'TITLE_FLAG_FIELD_REPORT': 'Flag Field Report',
	
	'BUTTON_APPLY': 'Apply',
	'BUTTON_OK': 'OK',
	'BUTTON_CANCEL': 'CANCEL',
	'BUTTON_CLEAR': 'CLEAR',
	'BUTTON_REMOVE': 'REMOVE',
	'BUTTON_SAVE': 'Save',
	'BUTTON_CLOSE': 'Close',
	'BUTTON_ADD_NEW_CARD': 'Add New Card',
	'BUTTON_ADD_DOCUMENTS': 'Add Documents',
	'BUTTON_ADD_DOCUMENT': 'Add Document',
	'BUTTON_ADD_USER': 'Add User',
	'BUTTON_REMOVE_SELECTED': 'Remove Selected',
	'BUTTON_LOG_IN': 'Log Back In',
	'BUTTON_NEW_FIELD_REPORT': 'New',
	'BUTTON_NEW_FORM': 'New Form',
	'BUTTON_DELETE_FORM': 'Delete Form',
	'BUTTON_ADD_PHOTO': 'Add Photo',
	'BUTTON_WEATHER_REPORT': 'Current Weather',
	'BUTTON_FIELDS': 'Fields',
	'BUTTON_SELECT': 'Select',

	'HEADING_DESIGNER': 'Designer',
	'HEADING_FORM_DESIGNER': 'Form Designer',
	'HEADING_DELETE_RECORD': 'Delete Record',
	'HEADING_SUBMIT_FIELD_REPORT': 'Send Field Report',
	'HEADING_COPY_FIELD_REPORT': 'Copy Field Report',
	'HEADING_DELETE_FIELD_REPORT': 'Delete Field Report',
	'HEADING_DELETE_FIELD_REPORT_LOG': 'Delete Log',

	'STATUS_ACTIVE': 'Active',
	'STATUS_INACTIVE': 'Inactive',
	'STATUS_UNVERIFIED': 'Unverified',

	'TOOLTIP_EDIT': 'Edit',
	'TOOLTIP_SUBMIT': 'Submit',
	'TOOLTIP_DELETE': 'Delete',
	'TOOLTIP_NEW': 'New',

	'WEATHER_REPORT': 'Weather Report',
	'MOVE_ITEMS_BETWEEN_LISTS_AND_CONTAINERS': 'Move Items Between Lists and Containers',
	'DRAG_CONTAINERS': 'Drag Containers',
	'GROUP_LIST_STYLE': 'Repeating Form',
	'ALLOW_MULTIPLE_FORM_ENTRIES': 'Repeating Form',
	'TITLE_EDIT_CATEGORY': 'Edit Category',
	'TITLE_ADD_CATEGORY': 'Add Category',
	'ERROR_DUPLICATE': 'This entry has already been added',
	'LIST_STYLE': 'Repeating Group',
	'INFO_CATEGORY_DELETED': 'The Category has been deleted',
	'HEADING_DELETE_CATEGORY': 'Delete Category',
	'INFO_OK_DELETE_CATEGORY': 'Pressing OK will delete this category:',
	'FORM_COMPONENT': 'Form Component',
	'TITLE_EDIT_FORM': 'Edit Form',
	'TITLE_ADD_FORM': 'Add Form',
	'TITLE_DESIGN_FORM': 'Design Form',
	'INFO_FORM_DELETED': 'The form has been deleted.',
	'HEADING_DELETE_FORM': 'Delete Form',
	'INFO_OK_DELETE_FORM': 'Pressing OK will delete this form:',
	'TITLE_EDIT_JOB': 'Edit Job',
	'TITLE_ADD_JOB': 'Add job',
	'INFO_JOB_DELETED': 'The job has been deleted.',
	'HEADING_DELETE_JOB': 'Delete Job',
	'INFO_OK_DELETE_JOB': 'Pressing OK will delete this job:',
	'CATEGORY': 'Category',
	'FORM': 'Form',
	'ASSIGNED_USER': 'Assigned User',
	'SEND_TO_USER': 'Send To User',
	'TITLE_EDIT_PROJECT': 'Edit Project',
	'TITLE_ADD_PROJECT': 'Add Project',
	'INFO_PROJECT_DELETED': 'The project has been deleted.',
	'HEADING_DELETE_PROJECT': 'Delete Project',
	'INFO_OK_DELETE_PROJECT': 'Pressing OK will delete this project:',
	'HEADING_PROJECTS': 'Projects',
	'HEADING_JOBS': 'Jobs',
	'HEADING_CATEGORIES': 'Categories',
	'HEADING_FORMS': 'Forms',

	'ICON': 'Icon'

};