// lang-es.ts

export const LANG_ES_NAME = 'es';

export const LANG_ES_TRANS = {
	'DATE_FORMAT': 'dd/mm/yyyy',
	'DATE_SEPERATOR': '/',

	'hello world': 'hola mundo',
	'HOME': 'Casa',
	'USER_ADMINISTRATION': 'Admin de usuarios',
	'PROJECT_MANAGEMENT': 'Gestión de Proyectos',
	'PROJECT_MANAGEMENT_ADMINISTRATION': 'Administración de proyectos',
	'CREATED_WITH': 'Creado con',
	'DC_COPYRIGHT': 'Dexter & Chaney, LLC. Todos los derechos reservados. No hay acceso no autorizado.',
	'DC_COPYRIGHT_YEAR': '1988-2017 ',
	'DC_WEB_PAGE_LINK': 'http://www.dexterchaney.com/',
	'EXTERNAL_LINK': 'Enlace externo',
	'LOG_OFF': 'Desconectar',
	'LOGGED_OFF': "Ha cerrado la sesión de la aplicación",
	'ACTION': 'Acción',
	'USER_LIST': 'Lista de usuarios',
	'NICK_NAME': 'Apodo',
	'GIVEN_NAME': 'Nombre de pila',
	'FAMILY_NAME': 'Apellido',
	'NAME': 'Nombre',
	'EMAIL': 'Email',
	'EMAIL_LOGON': 'E-mail / Acceso',
	'LAST_LOGIN': 'Último acceso',
	'CARD_STYLE': 'Estilo de tarjeta',
	'LABEL': 'Etiqueta',
	'HIDE': 'Esconder',
	'CLASS': 'Clase',
	'PLACEHOLDER': 'Marcador',
	'REQ': 'Nec',
	'READ': 'Leer',
	'VERIFIED': 'Verificado',
	'1_COLUMN': '1-Columna',
	'2_COLUMN': '2-Columna',
	'3_COLUMN': '3-Columna',
	'JOB': 'Trabajo',
	'OWNER': 'Asignado',
	'SEND_TO': 'Enviar a',
	'PHASE': 'Fase',
	'DATE': 'Fecha',
	'DESCRIPTION': 'Descripción',
	'PROJECT_MANAGER': 'Gerente de proyecto',
	'REPORT_DATE': 'Fecha del informe',
	'CARD_TITLE': 'Título de la Tarjeta',
	'REPORT_FLAGGED_REASONS': 'Informe de las razones marcadas',
	'PHOTO_GALLERY': 'galería de fotos',
	'FIELD_REPORT': 'Tablero',
	'FIELD': 'Campo',
	'SELECT_FIELD_COMPONENT': 'Seleccionar componente de formulario',

	'WEATHER': 'Clima',
	'TEMP': 'Temperatura',
	'WIND': 'Viento',
	'PRECIP': 'Precipitado',
	'EVENT': 'Evento',
	'SKY': 'Cielo',
	'GROUND': 'Suelo',
	'WEATHER_DELAY': 'Tiempo Delay',
	'PHOTO_ATTACHMENTS': 'Adjuntos de fotos',
	'PHOTO_ATTACHMENT': 'Adjuntos de foto',
	'CONDITION': 'Tiempo',
	'RH': 'RH',

	'SUBCONTRACTOR': 'Compañía de Subcontratistas',
	'WORKER_COUNT': 'Numero de trabajadores',
	'NOTES': 'Notas',
	'CREW': 'tripulación',

	'VISITOR_NAME': 'Nombre',
	'VISITOR': 'Visitante',
	'COMPANY': 'Empresa',
	'FOR': 'Razón de la visita',
	'TO_SEE': 'Reunirse con',
	'TIME_IN': 'Tiempo en',
	'TIME': 'Hora',
	'TIME_OUT': 'Se acabó el tiempo',
	'VISTOR_SIGNATURE': 'Firma',

	'WORK_COMPLETED': 'Trabajo completado',
	'LOCATION': 'Ubicación',

	'PHOTO': 'Foto',

	'OPEN_FIELD_REPORTS': 'Abrir informes de campo',
	'CLOSED_FIELD_REPORTS': 'Informes de Campo Presentados',

	'ERROR_ALL_LICENSES_ASSIGNED': 'Todas las licencias se han asignado',
	'ERROR_IS_REQUIRED': 'es requerido',
	'ERROR_NO_DOCUMENTS_FOR_CATEGORY': 'No se encontraron documentos para esta categoría',
  	'ERROR_SOMETHING_BAD_HAPPENED': 'La actualización no se ha procesado, por favor cierre sesión e inicie sesión o actualice la página',
	'ERROR_RECORD_NOT_ADDED_DUPLICATE': 'El registro no fue agregado, ya existe en la base de datos',
	'ERROR_CANNOT_REMOVE_LICENSE': 'No se puede eliminar la licencia de administrador de este usuario.',
	'ERROR_IS_INVALID': 'no es válido',
	'ERROR_DUPLICATE_FIELD_REPORT': 'Ya se ha creado un informe para esta tarea y fecha',

	'INFO_DOCUMENTS_ADDED': 'Documentos agregados',
	'INFO_DOCUMENT_ADDED': 'Documento agregado',
	'INFO_DOCUMENT_DELETED': 'Documento eliminado',
	'INFO_RECORD_DELETED': 'Registro eliminado',
	'INFO_USER_DELETED': 'Usuario eliminado correctamente',
	'INFO_OK_DELETE_RECORD': 'Al presionar OK se borrará este registro',
	'INFO_USER_ADDED': 'usuario agregado',
	'INFO_ROUTING_FAILURE': 'Lo sentimos, se ha producido un error, Por favor, presione el botón para mostrar su página!',
	'INFO_OK_SUBMIT_FIELD_REPORT': 'Al presionar OK enviará este informe al Project Manager',
	'INFO_FIELD_REPORT_SUBMITTED': 'El informe de campo ha sido enviado',
	'INFO_OK_COPY_FIELD_REPORT': 'Al pulsar Aceptar se copiará este informe y se creará un nuevo informe de campo',
	'INFO_FIELD_REPORT_COPIED': 'El informe de campo se ha copiado',
	'INFO_OK_DELETE_FIELD_REPORT': 'Al presionar OK se eliminará este informe: ',
	'INFO_FIELD_REPORT_DELETED': 'Se ha eliminado el informe de campo',
	'INFO_OK_DELETE_FIELD_REPORT_LOG': 'Al presionar OK, se eliminará esta entrada de registro: ',
	'INFO_FIELD_REPORT_LOG_DELETED': 'Se ha eliminado el registro del informe de campo.',


	'PLACEHOLDER_SEARCH': 'Buscar ...',
	'TITLE_BACK_TO_TOP': 'Volver arriba',
	'TITLE_ADD_NEW_USER': 'Añadir Usuario',
	'TITLE_ROUTING_FAILURE': 'OOPS!',
	'FIELD_REPORTING': 'Campo',
	'TITLE_ADD_FIELD_REPORT': 'Nuevo Informe de Campo',
	'TITLE_FLAG_FIELD_REPORT': 'Informe de campo de bandera',

	'BUTTON_APPLY': 'Aplicar',
	'BUTTON_OK': 'OK',
	'BUTTON_CANCEL': 'Cancelar',
	'BUTTON_CLEAR': 'CLARO',
	'BUTTON_REMOVE': 'RETIRAR',
	'BUTTON_SAVE': 'Salvar',
	'BUTTON_CLOSE': 'Cerca',
	'BUTTON_ADD_NEW_CARD': 'Añadir nueva tarjeta',
	'BUTTON_ADD_DOCUMENTS': 'Añadir documentos',
	'BUTTON_ADD_DOCUMENT': 'Añadir documento',
	'BUTTON_ADD_USER': 'Agregar usuario',
	'BUTTON_REMOVE_SELECTED': 'Eliminar selección',
	'BUTTON_LOG_IN': 'Regresar',
	'BUTTON_NEW_FIELD_REPORT': 'Abrir Nuevo Informe',
	'BUTTON_NEW_FORM': 'Nueva Forma',
	'BUTTON_DELETE_FORM': 'Eliminar formulario',
	'BUTTON_ADD_PHOTO': 'Añadir Foto',
	'BUTTON_WEATHER_REPORT': 'Clima actual',
	'BUTTON_FIELDS': 'Campos',
	'BUTTON_SELECT': 'Seleccionar',

	'HEADING_DESIGNER': 'Diseñador',
	'HEADING_FORM_DESIGNER': 'Diseñador de formularios',
	'HEADING_DELETE_RECORD': 'Eliminar registro',
	'HEADING_SUBMIT_FIELD_REPORT': 'Enviar informe de campo',
	'HEADING_COPY_FIELD_REPORT': 'Copiar el informe de campo',
	'HEADING_DELETE_FIELD_REPORT': 'Eliminar informe de campo',
	'HEADING_DELETE_FIELD_REPORT_LOG': 'Eliminar Registro',

	'STATUS_ACTIVE': 'Activo',
	'STATUS_INACTIVE': 'Inactivo',
	'STATUS_UNVERIFIED': 'Inconfirmado',

	'TOOLTIP_EDIT': 'Editar',
	'TOOLTIP_SUBMIT': 'Enviar',
	'TOOLTIP_NEW': 'Nuevo',
	'TOOLTIP_DELETE': 'Borrar',

	'WEATHER_REPORT': 'Reporte del clima',
	'MOVE_ITEMS_BETWEEN_LISTS_AND_CONTAINERS': 'Mover elementos entre listas y contenedores',
	'DRAG_CONTAINERS': 'Contenedores de arrastre',
	'GROUP_LIST_STYLE': 'Formulario de repetición',
	'ALLOW_MULTIPLE_FORM_ENTRIES': 'Formulario de repetición',
	'TITLE_EDIT_CATEGORY': 'Editar categoría',
	'TITLE_ADD_CATEGORY': 'añadir categoría',
	'ERROR_DUPLICATE': 'Esta entrada ya se ha añadido',
	'LIST_STYLE': 'Grupo de repetición',
	'INFO_CATEGORY_DELETED': 'Se ha eliminado la categoría',
	'HEADING_DELETE_CATEGORY': 'Eliminar categoría',
	'INFO_OK_DELETE_CATEGORY': 'Al presionar OK se eliminará esta categoría:',
	'FORM_COMPONENT': 'Componente del formulario',
	'TITLE_EDIT_FORM': 'Editar formulario',
	'TITLE_ADD_FORM': 'Añadir formulario',
	'TITLE_DESIGN_FORM': 'Formulario de diseño',
	'INFO_FORM_DELETED': 'Se ha eliminado el formulario.',
	'HEADING_DELETE_FORM': 'Eliminar formulario',
	'INFO_OK_DELETE_FORM': 'Al presionar OK se eliminará este formulario:',
	'TITLE_EDIT_JOB': 'Editar trabajo',
	'TITLE_ADD_JOB': 'Añadir trabajo',
	'INFO_JOB_DELETED': 'El trabajo se ha eliminado.',
	'HEADING_DELETE_JOB': 'Eliminar trabajo',
	'INFO_OK_DELETE_JOB': 'Al presionar OK se eliminará este trabajo:',
	'CATEGORY': 'Categoría',
	'FORM': 'Formar',
	'ASSIGNED_USER': 'Usuario asignado',
	'SEND_TO_USER': 'Enviar al usuario',
	'TITLE_EDIT_PROJECT': 'Editar proyecto',
	'TITLE_ADD_PROJECT': 'Agregar proyecto',
	'INFO_PROJECT_DELETED': 'Se ha eliminado el proyecto.',
	'HEADING_DELETE_PROJECT': 'Eliminar proyecto',
	'INFO_OK_DELETE_PROJECT': 'Al presionar OK se eliminará este proyecto:',
	'HEADING_PROJECTS': 'Proyectos',
	'HEADING_JOBS': 'Trabajos',
	'HEADING_CATEGORIES': 'Categorías',
	'HEADING_FORMS': 'Formularios',

};