// lang-en.ts

export const LANG_FR_NAME = 'fr';

export const LANG_FR_TRANS = {
	'DATE_FORMAT': 'dd/mm/yyyy',
	'DATE_SEPERATOR': '/',

	'hello world': 'Bonjour le monde',

	'HOME': 'Maison',
	'USER_ADMINISTRATION': 'Administration des utilisateurs',
	'PROJECT_MANAGEMENT': 'Gestion de Projet',
	'PROJECT_MANAGEMENT_ADMINISTRATION': 'Administration de gestion de projet',
	'CREATED_WITH': 'Créé avec',
	'DC_COPYRIGHT': "Dexter & Chaney, LLC. Tous les droits sont réservés. Pas d'accès non autorisé.",
	'DC_COPYRIGHT_YEAR': '1988-2017 ',
	'DC_WEB_PAGE_LINK': 'http://www.dexterchaney.com/',
	'EXTERNAL_LINK': 'lien externe',
	'LOG_OFF': 'Déconnexion',
	'LOGGED_OFF': "Vous avez déconnecté de l'application",
	'ACTION': 'Action',
	'USER_LIST': "liste d'utilisateur",
	'NICK_NAME': 'Surnom',
	'GIVEN_NAME': 'Prénom',
	'FAMILY_NAME': 'Nom de famille',
	'NAME': 'Prénom',
	'EMAIL': 'Email',
	'EMAIL_LOGON': 'E-mail / Connexion',
	'LAST_LOGIN': 'Dernière connexion',
	'CARD_STYLE': 'Style de carte',
	'LABEL': 'Étiquette',
	'HIDE': 'Cacher',
	'CLASS': 'Classe',
	'PLACEHOLDER': 'Placeholder',
	'REQ': 'Req',
	'READ': 'Lis',
	'VERIFIED': 'Vérifié',
	'1_COLUMN': '1-Colonne',
	'2_COLUMN': '2-Colonne',
	'3_COLUMN': '3-Colonne',
	'JOB': 'Emploi',
	'OWNER': 'Attribué',
	'SEND_TO': 'Envoyer à',
	'PHASE': 'Phase',
	'DATE': 'La Date',
	'DESCRIPTION': 'La description',
	'PROJECT_MANAGER': 'Chef de projet',
	'REPORT_DATE': 'Date du compte rendu',
	'CARD_TITLE': 'Titre de la Carte',
	'REPORT_FLAGGED_REASONS': 'Rapport signalé Motifs',
	'PHOTO_GALLERY': 'galerie de photos',
	'FIELD_REPORT': 'Tableau de bord',
	'FIELD': 'Champ',
	'SELECT_FIELD_COMPONENT': 'Sélectionnez le composant Formulaire',

	'WEATHER': 'Météo',
	'TEMP': 'Temp',
	'WIND': 'Vent',
	'PRECIP': 'Précipitations',
	'EVENT': 'un événement',
	'SKY': 'Ciel',
	'GROUND': 'Sol',
	'WEATHER_DELAY': 'Délai de temps',
	'PHOTO_ATTACHMENTS': 'Pièces jointes',
	'PHOTO_ATTACHMENT': 'Pièces jointes',
	'CONDITION': 'Temps',
	'RH': 'RH',

	'SUBCONTRACTOR': 'Société de sous-traitance',
	'WORKER_COUNT': 'Nombre de travailleurs',
	'NOTES': 'Remarques',
	'CREW': 'équipage',

	'VISITOR_NAME': 'prénom',
	'VISITOR': 'Visiteur',
	'COMPANY': 'Compagnie',
	'FOR': 'Raison de visite',
	'TO_SEE': 'Rencontrer',
	'TIME_IN': 'Heure dedans',
	'TIME': 'Temps',
	'TIME_OUT': 'Temps libre',
	'VISTOR_SIGNATURE': 'Signature',

	'WORK_COMPLETED': 'Travaux achevés',
	'LOCATION': 'Emplacement',

	'PHOTO': 'Photo',
	'SIGNATURE': 'Signature',

	'OPEN_FIELD_REPORTS': 'Rapports de terrain ouverts',
	'CLOSED_FIELD_REPORTS': 'Rapports de terrain soumis',

	'ERROR_ALL_LICENSES_ASSIGNED': 'Toutes les licences ont été attribuées',
	'ERROR_IS_REQUIRED': 'est requis',
	'ERROR_NO_DOCUMENTS_FOR_CATEGORY': 'Aucun document trouvé pour cette catégorie',
	'ERROR_SOMETHING_BAD_HAPPENED': "La mise à jour n'a pas été traitée, veuillez vous déconnecter et vous connecter ou actualiser la page",
	'ERROR_RECORD_NOT_ADDED_DUPLICATE': "L'enregistrement n'a pas été ajouté, il existe déjà dans la base de données",
	'ERROR_CANNOT_REMOVE_LICENSE': "La licence d'administrateur ne peut pas être supprimée de cet utilisateur",
	'ERROR_IS_INVALID': "n'est pas valide",
	'ERROR_DUPLICATE_FIELD_REPORT': 'Un rapport pour ce poste et cette date a déjà été créé',

	'INFO_DOCUMENTS_ADDED': 'Documents ajoutés',
	'INFO_DOCUMENT_ADDED': 'Document ajoutée',
	'INFO_DOCUMENT_DELETED': 'Document supprimé',
	'INFO_RECORD_DELETED': 'Enregistrement supprimé',
	'INFO_USER_DELETED': 'Utilisateur supprimé avec succès',
	'INFO_OK_DELETE_RECORD': 'Appuyez sur OK pour supprimer cet enregistrement',
	'INFO_USER_ADDED': 'utilisateur ajoutée',
	'INFO_ROUTING_FAILURE': "Désolé, une erreur s'est produite, S'il vous plaît appuyez sur le bouton pour afficher votre page!",
	'INFO_OK_SUBMIT_FIELD_REPORT': 'Appuyez sur OK pour envoyer ce rapport au gestionnaire de projet',
	'INFO_FIELD_REPORT_SUBMITTED': 'Le rapport de terrain a été envoyé',
	'INFO_OK_COPY_FIELD_REPORT': 'Appuyez sur OK pour copier ce rapport et créer un nouveau rapport de champ',
	'INFO_FIELD_REPORT_COPIED': 'Le rapport de terrain a été copié',
	'INFO_OK_DELETE_FIELD_REPORT': 'Appuyez sur OK pour supprimer ce rapport: ',
	'INFO_FIELD_REPORT_DELETED': 'Le rapport sur le terrain a été supprimé',
	'INFO_OK_DELETE_FIELD_REPORT_LOG': 'En appuyant sur OK, vous effacez cette entrée de journal: ',
	'INFO_FIELD_REPORT_LOG_DELETED': 'Le journal des rapports de terrain a été supprimé.',


	'PLACEHOLDER_SEARCH': 'Rechercher ...',
	'TITLE_BACK_TO_TOP': 'Retour au sommet',
	'TITLE_ADD_NEW_USER': 'Ajouter un Utilisateur',
	'TITLE_ROUTING_FAILURE': 'OOPS!',
	'FIELD_REPORTING': 'Terrain',
	'TITLE_ADD_FIELD_REPORT': 'Nouveau rapport de terrain',
	'TITLE_FLAG_FIELD_REPORT': 'Rapport de champ de drapeau',

	'BUTTON_APPLY': 'Appliquer',
	'BUTTON_OK': 'OK',
	'BUTTON_CANCEL': 'ANNULER',
	'BUTTON_CLEAR': 'CLAIR',
	'BUTTON_REMOVE': 'RETIRER',
	'BUTTON_SAVE': 'Sauvegarder',
	'BUTTON_CLOSE': 'Fermer',
	'BUTTON_ADD_NEW_CARD': 'Ajouter une nouvelle carte',
	'BUTTON_ADD_DOCUMENTS': 'Ajouter des documents',
	'BUTTON_ADD_DOCUMENT': 'Ajouter un document',
	'BUTTON_ADD_USER': 'Ajouter un utilisateur',
	'BUTTON_REMOVE_SELECTED': 'Enlever la sélection',
	'BUTTON_LOG_IN': 'Connexion',
	'BUTTON_NEW_FIELD_REPORT': 'Ouvrir un Nouveau Rapport',
	'BUTTON_NEW_FORM': 'Nouvelle Forme',
	'BUTTON_DELETE_FORM': 'Supprimer le formulaire',
	'BUTTON_ADD_PHOTO': 'Ajouter un Photo',
	'BUTTON_WEATHER_REPORT': 'Météo actuelle',
	'BUTTON_FIELDS': 'Des champs',
	'BUTTON_SELECT': 'Sélectionner',

	'HEADING_DESIGNER': 'Designer',
	'HEADING_FORM_DESIGNER': 'Concepteur de formulaires',
	'HEADING_DELETE_RECORD': 'Supprimer un enregistrement',
	'HEADING_SUBMIT_FIELD_REPORT': 'Envoyer un rapport sur le terrain',
	'HEADING_COPY_FIELD_REPORT': 'Copier le rapport sur le terrain',
	'HEADING_DELETE_FIELD_REPORT': 'Supprimer le rapport sur le terrain',
	'HEADING_DELETE_FIELD_REPORT_LOG': 'Supprimer le journal',

	'STATUS_ACTIVE': 'actif',
	'STATUS_INACTIVE': 'Inactif',
	'STATUS_UNVERIFIED': 'Non vérifié',

	'TOOLTIP_EDIT': 'Modifier',
	'TOOLTIP_SUBMIT': 'Soumettre',
	'TOOLTIP_DELETE': 'Effacer',
	'TOOLTIP_NEW': 'Nouveau',

	'WEATHER_REPORT': 'Bulletin météo',
	'MOVE_ITEMS_BETWEEN_LISTS_AND_CONTAINERS': 'Déplacer les éléments entre les listes et les conteneurs',
	'DRAG_CONTAINERS': 'Conteneurs à glisser',
	'GROUP_LIST_STYLE': 'Repeating Form',
	'ALLOW_MULTIPLE_FORM_ENTRIES': 'Formulaire répétitif',
	'TITLE_EDIT_CATEGORY': 'Modifier la catégorie',
	'TITLE_ADD_CATEGORY': 'ajouter une catégorie',
	'ERROR_DUPLICATE': "L'entrée a déjà été ajoutée",
	'LIST_STYLE': 'Groupe répétitif',
	'INFO_CATEGORY_DELETED': 'La catégorie a été supprimée',
	'HEADING_DELETE_CATEGORY': 'Supprimer la catégorie',
	'INFO_OK_DELETE_CATEGORY': 'En appuyant sur OK, vous supprimez cette catégorie:',
	'FORM_COMPONENT': 'Composante du formulaire',
	'TITLE_EDIT_FORM': "Formulaire d'édition",
	'TITLE_ADD_FORM': 'Ajouter un formulaire',
	'TITLE_DESIGN_FORM': 'Formulaire de conception',
	'INFO_FORM_DELETED': 'Le formulaire a été supprimé.',
	'HEADING_DELETE_FORM': 'Supprimer le formulaire',
	'INFO_OK_DELETE_FORM': 'En appuyant sur OK, vous supprimez ce formulaire:',
	'TITLE_EDIT_JOB': "Modifier l'emploi",
	'TITLE_ADD_JOB': 'Ajouter un emploi',
	'INFO_JOB_DELETED': 'Le travail a été supprimé.',
	'HEADING_DELETE_JOB': 'Supprimer le travail',
	'INFO_OK_DELETE_JOB': 'En appuyant sur OK, vous supprimez ce travail:',
	'CATEGORY': 'Catégorie',
	'FORM': 'Forme',
	'ASSIGNED_USER': 'Utilisateur affecté',
	'SEND_TO_USER': "Envoyer à l'utilisateur",
	'TITLE_EDIT_PROJECT': 'Modifier le projet',
	'TITLE_ADD_PROJECT': 'Ajouter un projet',
	'INFO_PROJECT_DELETED': 'Le projet a été supprimé.',
	'HEADING_DELETE_PROJECT': 'Supprimer le projet',
	'INFO_OK_DELETE_PROJECT': 'En appuyant sur OK, vous supprimez ce projet:',
	'HEADING_PROJECTS': 'Projets',
	'HEADING_JOBS': 'Emplois',
	'HEADING_CATEGORIES': 'Catégories',
	'HEADING_FORMS': 'Formes',

};